#+TITLE: test
#+OPTIONS: toc:nil
#+STARTUP: showall indent
#+STARTUP: hidestars
---
sidebar: auto
---
* single cell sequencing
The breakthrough of single cell sequencing is to locate the resolution of the study to a single cell, which avoids the influence of a large number of non-research impurity cells in the cell mass (bulk) on the data analysis after taking the mean value. Thus, the gene expression level of cells can be analyzed more accurately.

At present, the main high-throughput sequencing methods are 10X and BD, there are some technical differences, but both of them can be used for large cell volume measurement, the disadvantage is that the single cell gene expression mining is not deep, suitable for screening specific genes. Smart is non-high throughput sequencing, but gene data mining is more in-depth and suitable for the screening of specific target genes of interest.

Single cell sequencing first divides the tissue into single cells by micromanipulation, limited dilution, flow cytometry sorting or microfluidic chip, and then reverse transcribes its RNA into double-stranded cDNA amplification library, and then ultrasonic interrupts cDNA to repair the end of PCR,. Finally, the sequencing analysis was carried out.

The significance of single cell sequencing in the field of tumor can be divided into two parts: the heterogeneity of tumor parenchyma cells, the study of drug resistance, and the study of the mechanism of immune cells in tumor microenvironment and stroma cells in the process of tumorigenesis and development.

